export { default as isChar } from "./isChar.ts";
export { default as isFilterable } from "./isFilterable.ts";
export { default as isIterable } from "./isIterable.ts";
export { default as isIterator } from "./isIterator.ts";
export { default as isMappable } from "./isMappable.ts";
export { default as isObject } from "./isObject.ts";
export { default as isPromise } from "./isPromise.ts";
export { default as isReducible } from "./isReducible.ts";
export { default as isString } from "./isString.ts";
