name: Deploy to JSR

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check packages
        run: |
          deno fmt --check
          deno lint
          deno test --allow-all --coverage=cov/
          deno coverage --lcov cov/ > cov.lcov

      - name: Get current version
        id: get_version
        run: |
          current_version=$(jq -r '.version' deno.json)
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Deploy to JSR
        run: |
          deno publish
